### ISSUE TITLE
Organize the repo as suggedted by Smarttings

### ISSUE THREAD

**Issue by yohcop** [augoisms/smartthings#1]
http://docs.smartthings.com/en/latest/tools-and-ide/github-integration.html#repository-structure

This will make it easy to clone and update the files directly from the smartthings IDE!
It should be simple, just move the files around in sub directories.

**Comment by augoisms** [comment]
Done!

**Comment by yohcop** [comment]
That was quick :)

I do get an error though, it's inclear to me why: `Updated 0 devices and created 0 new devices (1 skipped due to errors)`

The groovy files were working just fine when I copy-pasted them though.
Any idea how to see those errors from the smartthings IDE?

**Comment by augoisms** [comment]
To be honest, I have not tried the integration. I didn't like the wide sweeping permissions it requests and since I have work-related stuff attached to my account I opted to not use it.

**Comment by yohcop** [comment]
Fair enough. I'll dig a bit more, and let you know if I find answers or solutions...
Thanks!
